CREATE DATABASE RACEDAYDB;
USE RACEDAYDB;

CREATE TABLE Roles(RoleId INT IDENTITY(1,1) PRIMARY KEY,
RoleName VARCHAR(20) NOT NULL UNIQUE);

CREATE TABLE Users(UserId INT IDENTITY(1,1) PRIMARY KEY,
FullName VARCHAR(100) NOT NULL,
Email VARCHAR(100) NOT NULL UNIQUE,
PasswordHash VARCHAR(255) NOT NULL,
RoleId INT NOT NULL,
Createdat DATETIME NOT NULL DEFAULT GETDATE(),
FOREIGN KEY(RoleId) REFERENCES Roles(RoleId));
