CREATE DATABASE RACEDAYDB;
USE RACEDAYDB;

CREATE TABLE Roles(RoleId INT IDENTITY(1,1) PRIMARY KEY,
RoleName VARCHAR(20) NOT NULL UNIQUE);

CREATE TABLE Users(UserId INT IDENTITY(1,1) PRIMARY KEY,
FullName VARCHAR(100) NOT NULL,
Email VARCHAR(100) NOT NULL UNIQUE,
PasswordHash VARCHAR(255) NOT NULL,
RoleId INT NOT NULL,
Createdat DATETIME NOT NULL DEFAULT GETDATE(),
FOREIGN KEY(RoleId) REFERENCES Roles(RoleId));

CREATE TABLE Events (EventId INT IDENTITY(1,1) PRIMARY KEY,
EventName VARCHAR(150) NOT NULL,
EventDate DATE NOT NULL,
Location VARCHAR(150) NOT NULL,
Description VARCHAR(MAX) NULL,
OrganiserId INT NOT NULL,
CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
FOREIGN KEY(OrganiserId) REFERENCES USERS(UserId));

CREATE TABLE Categories(CategoryId INT IDENTITY(1,1) PRIMARY KEY,
EventId INT NOT NULL,
CategoryName VARCHAR(50) NOT NULL,
DistanceKm DECIMAL(5,2) NOT NULL,
MaxParticipants INT NOT NULL DEFAULT 100,
EntryFee DECIMAL(8,2) NOT NULL DEFAULT 0,
FOREIGN KEY(EventId) REFERENCES Events(EventId));